### ISSUE TITLE
Monitoring Instance="*" issues

### ISSUE THREAD

**Issue by pall-valmundsson** [bloomberg/collectdwin#12]
When a PerformanceCounter instance disappears an exception is thrown and the whole metric collection run gets cancelled.

In my case I'm monitoring "*" instances for some .NET counters. While testing I had the "Services" MMC snap-in open to start the service, when I close MMC the following exception is thrown which illustrates the issue.

```
2015-09-16 21:00:56.1830|ERROR|BloombergFLP.CollectdWin.MetricsCollector: ReadThreadProc() got exception : 
EXCEPTION: System.InvalidOperationException: Instance 'mmc' does not exist in the specified Category.
   at System.Diagnostics.CounterDefinitionSample.GetInstanceValue(String instanceName)
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at BloombergFLP.CollectdWin.WindowsPerformanceCounterPlugin.Read()
```

When going through the code I also noticed that any new instance that could appear as processes start will not get added as that's only done at startup.

I guess catching [InvalidOperationException](https://msdn.microsoft.com/en-us/library/system.diagnostics.performancecounter.nextvalue%28v=vs.110%29.aspx) when [reading NextValue()](https://github.com/bloomberg/collectdwin/blob/master/src/CollectdWinService/WindowsPerformanceCounterPlugin.cs#L90) and removing the counter and returning null fixes the first issue. The second issue, adding new counters, requires enumerating all Instance="*" counters at some interval which might be expensive (don't know).

It seems that to monitor any userland processes they will all need to have successfully started before CollectdWin starts, and they will need to stay up for _any_ metrics to get sent from the host. I guess the same goes for named instances of userland processes; if they're not available at startup, they won't get added to the list of monitored metrics.

**Comment by pall-valmundsson** [comment]
I'm willing to cook something up, but would like some discussion about which way to do this.

The easiest way would be to re-evaluate the config on each iteration to look for "*" metrics and re-enumerate the counters. That's probably way too expensive.

Another might be to re-evaluate at a given interval, could be a multiplier of intervals.

There might be some way to subscribe to events for when counters are added, I haven't really looked.

Any thoughts?

**Comment by yogeswaran** [comment]
Subscribing to performance counter events will be the correct thing to do, I searched for it but didn't find any. Re-evaluating "*" instances on every interval might be too expensive. I like the idea of re-evaluating every Nth configured interval.

btw, we may need to re-evaluate everything (almost like calling configure() for every Nth interval) because if CollectdWin started before an application was started, getting counter value will fail and the counter will be removed from the list forever (even though application started later and counter became a valid counter).

**Comment by pall-valmundsson** [comment]
Ok. Property name `RefreshInterval`? Should the property be set in GeneralSettings? If so all plugins will get a `.Configure()` call, which probably doesn't make sense. Otherwise a new property in `WindowsPerformanceCounterPluginConfig` which limits the scope to that plugin, which might seem strange.

Thoughts?

**Comment by yogeswaran** [comment]
At this time it makes sense to have it only for WindowsPerformanceCounter plugin, in future if there is a need we can move it to a global settings.

Does this configuration make sense?

```
<WindowsPerformanceCounter>
  <ReloadConfiguration Enable="true" Interval=900 />
  <Counters>
    <Counter Category="Processor" Name="% Processor Time" Instance="_Total" CollectdPlugin="aggregation" CollectdPluginInstance="cpu-average" CollectdType="cpu" CollectdTypeInstance="processor" />
   ...
  </Counters>
</WindowsPerformanceCounter>
```

**Comment by pall-valmundsson** [comment]
Yes this makes sense, I'll try to look at this. Probably won't be until next week though.

**Comment by yogeswaran** [comment]
Rather than reloading configuration at Nth interval, should we load it after 'interval' seconds, ie read() calls configure() only when if currentTime > (lastConfigureTime + interval).

Sorry for not making it clear before.

**Comment by pall-valmundsson** [comment]
That is a lot cleaner. I force pushed the changes to the PR.
