### ISSUE TITLE
Add an option to specify instance name

### ISSUE THREAD

**Issue by tpoindessous** [bloomberg/collectdwin#40]
Hi

we would like to use collectdwin, with a new gateway, [greedee](https://github.com/yanc0/greedee)

We would like to specify the instance name in CollectdWin config file, instead of relying on machine name and dns resolution.

In this file, it seems that you get the instance name via a function. Could it be to add a new option var in config file ?

https://github.com/bloomberg/collectdwin/blob/308e7dd6f7c9a721b75ba7249b2818001b77d209/src/CollectdWinService/WindowsPerformanceCounterPlugin.cs#L100

Thanks !

**Comment by tpoindessous** [comment]
Hi 

I tried to do in #41 

Thanks.

**Comment by yogeswaran** [comment]
This is fixed in #41
